services:
  next_humble_stack_drizzle_gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    container_name: next_humble_stack_drizzle_gateway
    restart: always
    ports:
      - "4983:4983"
    environment:
      PORT: "4983"
      STORE_PATH: "/app/data"
    volumes:
      - next_humble_stack_drizzle_gateway:/app/data

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: humble_stack
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
  next_humble_stack_drizzle_gateway:
